apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: facturacion
type: Opaque
data:
  # postgres password: "postgres" (base64)
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # oracle password: "oracle" (base64)
  ORACLE_PASSWORD: b3JhY2xl
