apiVersion: v1
kind: Secret
metadata:
  name: clientes-secret
  namespace: facturacion
  labels:
    app: clientes-service
    component: secret
type: Opaque
stringData:
  # PostgreSQL Password
  POSTGRES_PASSWORD: "castor_pass"
  SPRING_DATASOURCE_PASSWORD: "castor_pass"
