apiVersion: v1
kind: Service
metadata:
  name: clientes-service
  namespace: facturacion
  labels:
    app: clientes-service
    tier: application
spec:
  type: ClusterIP
  selector:
    app: clientes-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  sessionAffinity: None
