apiVersion: v1
kind: Secret
metadata:
  name: facturacion-secret
  namespace: facturacion
  labels:
    app: facturacion-service
    component: secret
type: Opaque
stringData:
  # Oracle Password
  ORACLE_PASSWORD: "castor_pass"
  SPRING_DATASOURCE_PASSWORD: "castor_pass"
